# Generated by Django 5.0.2 on 2024-03-25 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(blank=True)),
                ("last_name", models.TextField(blank=True)),
                ("birthday", models.DateField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        default="default_profile_picture.jpg",
                        upload_to="profile_pictures/",
                    ),
                ),
                ("viewed_recipes", models.JSONField(blank=True, default=list)),
                ("user_recipe_ids", models.JSONField(default=list)),
                ("ingredient_preferences", models.JSONField(default=list)),
                ("ingredient_user_ids", models.JSONField(default=list)),
                ("created_recipes", models.JSONField(default=list)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("User", "User"),
                            ("Admin", "Admin"),
                            ("Moderator", "Moderator"),
                        ],
                        default="User",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
