# Generated by Django 5.0.2 on 2024-03-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="biography",
            field=models.TextField(blank=True),
        ),
    ]
