# Generated by Django 5.0.2 on 2024-03-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='media/profile_pictures/'),
        ),
    ]
