# Generated by Django 5.0.2 on 2024-04-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cooking_time', models.IntegerField()),
                ('servings', models.PositiveIntegerField()),
                ('difficulty', models.IntegerField(choices=[(0, 'Learning'), (1, 'Home Cook'), (2, 'Culinary Chef'), (3, 'Gourmet Chef'), (4, 'Master Chef')])),
                ('steps', models.TextField()),
                ('average_rating', models.FloatField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
