# Generated by Django 5.0.2 on 2024-04-19 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_biography_and_more'),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('DI', 'Dinner'), ('S', 'Snack'), ('DE', 'Dessert')], default='B', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ManyToManyField(related_name='cuisines', to='recipe.cuisine'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='recipe.ingredient'),
        ),
    ]
