# Generated by Django 5.0.2 on 2024-04-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_alter_userprofile_biography_and_more"),
        ("recipe", "0002_cuisine_ingredient_recipe_author_recipe_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cookbook",
            fields=[
                ("cookbook_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Untitled Cookbook", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.userprofile",
                    ),
                ),
                (
                    "recipes",
                    models.ManyToManyField(
                        related_name="cookbooks", to="recipe.recipe"
                    ),
                ),
            ],
        ),
    ]
