# Generated by Django 5.0.2 on 2024-04-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0003_cookbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookbook",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="cookbook_images/"
            ),
        ),
    ]
